---
name: 🔖 Pull Request Labeler
on:
  pull_request_target: {}

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: 🚀 Run Labeler
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
        with:
          repo-token: ${{ github.token }}
          sync-labels: false
